Update linter's workflow for Ruby on Rails
microverseinc/linters-config pull request #127
Opened 2021-02-11 19:59 UTC by NoTengoBattery

# Using the latest linter's version by default

The official recommendation is to use the latest stable version of the linters for new projects. Since this repository is mainly used for new projects, it should stick to the recommendation.

By removing the explicit version from the workflow, new projects based on this repository will use the linter's latest version by default. This helps to:
  1. Remove the discrepancy between the development machine using a newer version and the workflow using an older version.
  2. Avoid the need to constantly updating this file to change the linter's version.
  3. Stick to the recommendation by using the latest stable version by default for new projects.

As a proof of concept, please check the following demonstration pull request using the proposed changes contained in this pull request: https://github.com/NoTengoBattery/installing-rails/pull/1.

Any comments are welcome. If you have any problem with this code, discuss it in this pull request. For code in the master/main branch, please open a GitHub Issue [here](https://github.com/notengobattery/linters-config/issues).

2021-03-09 17:58 UTC, euqueme approved these changes
Thank you @NoTengoBattery this is a great catch :raised_hands:  it's a yes for me :handshake: 

@bolah2009 what do you think?

2021-03-10 17:44 UTC, bolah2009 commented
It's okay for me. However, breaking changes are also introduced in the lastest version. This may cause many issues too where there may be a false negative of the failing test caused by breaking changes in linter.

WDYT @uryelah

2021-03-19 15:19 UTC, uryelah commented
@bolah2009 Yes, I don't think installing the latest version by default would be a good idea, maybe it could work if we also included the `--legacy-peer-deps` flag, but it still doesn't look like a very safe choice.

2021-03-19 15:28 UTC, NoTengoBattery commented
@bolah2009 and @bolah2009
A challenging question to you:

Is it better to have issues with the new code? The linter rejects a perfectly valid Ruby 3.0 source code already, so I don't see why it would matter if updating the linter brings issues when the old linter already has issues.

Despite that, as long as the GitHub version is in sync with the developer's version, there should not be issues. After all, the latest Rubucop version installed by default with Bundle is a stable release, not beta or testing or something like that.

2021-03-19 15:59 UTC, Spayco commented
@NoTengoBattery can you tell me why we need to update to ruby 3? is there any particular reason?
the setup instructions for microverse students uses ruby 2.7, so our linters should work on that more than any other version

2021-03-19 16:05 UTC, NoTengoBattery commented
@Spayco 
That was a particular example. Nobody is asking anybody to use any version of anything besides the latest rubocop.

You are still forgetting the discrepancy between the local machine version and the workflow version. Either fix the workflow's version or add in the "instructions" a requirement to install a particular ancient version of the linter.

2021-03-19 16:07 UTC, NoTengoBattery commented
@Spayco 
Please give me a particular reason for installing an ancient version of a linter for new projects when the project is supposed to be **new**. Is stability a concern? Because I am aware, that is not, since rubocop is a mature tool.

2021-03-19 17:00 UTC, bolah2009 commented
@NoTengoBattery Packages includes breaking changes. This includes changes that might not be compatible with the config files we have. We can't use "lastest version" of these packages. There's a difference between using "lastest version" and "stable version". So "lastest version" is a no. 

@NoTengoBattery Can we do this:
- Let's fix the version to latest major version, this way, we can be sure that no sudden future updates will break the associated config files. e.g rubocop should be fixed to 1.x, stylelint should be fixed to 18.x.

What do you think @NoTengoBattery ?

2021-03-19 17:02 UTC, bolah2009 requested changes
Thanks for this PR @NoTengoBattery 

Please see the comments

2021-03-19 17:02 UTC, bolah2009 commented on ror/.github/workflows/linters.yml
> +          gem install --no-document rubocop # https://docs.rubocop.org/en/stable
Let' still use the fix version. But it can be a major version instead.

2021-03-19 17:02 UTC, bolah2009 commented on ror/.github/workflows/linters.yml
> +    runs-on: ubuntu-20.04
I think this is good, thanks 👍🏽

2021-03-19 17:02 UTC, bolah2009 commented on ror/.github/workflows/linters.yml
> +          node-version: ">=15.x"
This affects npm, can we agree on a fixed major version instead?

2021-03-19 17:02 UTC, bolah2009 commented on ror/.github/workflows/linters.yml
> +          npm install --save-dev stylelint stylelint-scss stylelint-config-standard stylelint-csstree-validator
Please let's no remove the fixed versions, at least, let's keep the major versions.

2021-03-19 17:10 UTC, NoTengoBattery commented
@bolah2009 

For doing that, this pull request makes no sense, so I'll close it. If you note, the configuration is already updated, so I see no argument against it. The latest version is always backward compatible with the old config, because as I said: **rubocop is a mature tool**. So is stylelint.

2021-03-19 17:10 UTC, closed without merging